# Generated by Django 4.2.7 on 2024-01-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='', max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
