# Generated by Django 4.2.7 on 2024-01-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verification_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
