# Generated by Django 4.2.7 on 2023-12-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.TextField(default='', verbose_name='fio'),
        ),
        migrations.AddField(
            model_name='masssend',
            name='end_time',
            field=models.DateTimeField(auto_now=True, verbose_name='end time'),
        ),
        migrations.AddField(
            model_name='masssend',
            name='start_time',
            field=models.DateTimeField(auto_now=True, verbose_name='start time'),
        ),
    ]
