# Generated by Django 4.2.7 on 2023-12-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_client_full_name_masssend_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masssend',
            name='end_time',
            field=models.DateTimeField(verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='masssend',
            name='start_time',
            field=models.DateTimeField(verbose_name='start time'),
        ),
    ]
