# Generated by Django 4.2.7 on 2024-01-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_alter_masssend_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='masssend',
            name='banned',
            field=models.BooleanField(default=False, verbose_name='Заблокирована'),
        ),
    ]
