# Generated by Django 4.2.7 on 2023-12-02 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sender', '0003_alter_masssend_end_time_alter_masssend_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masssend',
            name='clients',
        ),
        migrations.AddField(
            model_name='masssend',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name of group')),
                ('clients', models.ManyToManyField(to='sender.client', verbose_name='clients')),
            ],
        ),
        migrations.AddField(
            model_name='masssend',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sender.clientgroup', verbose_name='group'),
        ),
    ]
