# Generated by Django 4.2.7 on 2023-12-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_remove_masssend_clients_masssend_owner_clientgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masssend',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='masssend',
            name='start_time',
        ),
        migrations.AddField(
            model_name='masssend',
            name='end_date',
            field=models.DateTimeField(auto_now=True, verbose_name='end time'),
        ),
        migrations.AddField(
            model_name='masssend',
            name='start_date',
            field=models.DateTimeField(auto_now=True, verbose_name='start time'),
        ),
    ]
