# Generated by Django 4.2.7 on 2024-01-15 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_masssend_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='server_response',
        ),
    ]
