# Generated by Django 4.2.7 on 2023-12-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0005_remove_masssend_end_time_remove_masssend_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masssend',
            name='end_date',
            field=models.DateTimeField(verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='masssend',
            name='start_date',
            field=models.DateTimeField(verbose_name='start time'),
        ),
    ]
