# Generated by Django 4.2.7 on 2023-12-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0006_alter_masssend_end_date_alter_masssend_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masssend',
            name='end_date',
            field=models.DateField(auto_now=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='masssend',
            name='start_date',
            field=models.DateField(auto_now=True, verbose_name='start date'),
        ),
    ]
