# Generated by Django 4.2.7 on 2023-12-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0009_alter_client_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='masssend',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='name'),
        ),
    ]
