# Generated by Django 4.2.7 on 2023-12-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0011_clientgroup_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientgroup',
            name='owner',
        ),
    ]
