# Generated by Django 4.2.7 on 2023-12-14 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sender', '0013_clientgroup_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date of attempt')),
                ('is_sent', models.BooleanField(verbose_name='is_sent')),
                ('server_response', models.IntegerField(verbose_name='server_response')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.masssend', verbose_name='send')),
            ],
        ),
    ]
