# Generated by Django 4.2.7 on 2024-01-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/previews/', verbose_name='Картинка')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата публикации')),
            ],
        ),
    ]
